# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SIMPLER_GUI_designtabs.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(970, 572)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 961, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.SIMPLER = QtWidgets.QWidget()
        self.SIMPLER.setObjectName("SIMPLER")
        self.lineEdit_maxdist = QtWidgets.QLineEdit(self.SIMPLER)
        self.lineEdit_maxdist.setGeometry(QtCore.QRect(250, 148, 41, 20))
        self.lineEdit_maxdist.setObjectName("lineEdit_maxdist")
        self.label_14 = QtWidgets.QLabel(self.SIMPLER)
        self.label_14.setGeometry(QtCore.QRect(160, 150, 81, 16))
        self.label_14.setObjectName("label_14")
        self.groupBox_2 = QtWidgets.QGroupBox(self.SIMPLER)
        self.groupBox_2.setGeometry(QtCore.QRect(160, 180, 131, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_N0 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_N0.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit_N0.setObjectName("lineEdit_N0")
        self.lineEdit_lambdaem = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_lambdaem.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.lineEdit_lambdaem.setObjectName("lineEdit_lambdaem")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_5.setObjectName("label_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.SIMPLER)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 320, 141, 121))
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_ni = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_ni.setGeometry(QtCore.QRect(10, 40, 61, 20))
        self.lineEdit_ni.setObjectName("lineEdit_ni")
        self.lineEdit_ns = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_ns.setGeometry(QtCore.QRect(10, 90, 61, 20))
        self.lineEdit_ns.setObjectName("lineEdit_ns")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_18.setObjectName("label_18")
        self.groupBox_6 = QtWidgets.QGroupBox(self.SIMPLER)
        self.groupBox_6.setGeometry(QtCore.QRect(160, 320, 131, 121))
        self.groupBox_6.setObjectName("groupBox_6")
        self.lineEdit_angle = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_angle.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit_angle.setObjectName("lineEdit_angle")
        self.lineEdit_lambdaex = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_lambdaex.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.lineEdit_lambdaex.setObjectName("lineEdit_lambdaex")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_10.setObjectName("label_10")
        self.groupBox_vis = QtWidgets.QGroupBox(self.SIMPLER)
        self.groupBox_vis.setGeometry(QtCore.QRect(530, 10, 411, 501))
        self.groupBox_vis.setObjectName("groupBox_vis")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_vis)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 311, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.scatterlayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.scatterlayout.setContentsMargins(0, 0, 0, 0)
        self.scatterlayout.setObjectName("scatterlayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_vis)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 270, 311, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.scatterlayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.scatterlayout_2.setContentsMargins(0, 0, 0, 0)
        self.scatterlayout_2.setObjectName("scatterlayout_2")
        self.groupBox_largeROI = QtWidgets.QGroupBox(self.groupBox_vis)
        self.groupBox_largeROI.setGeometry(QtCore.QRect(80, 230, 221, 91))
        self.groupBox_largeROI.setObjectName("groupBox_largeROI")
        self.pushButton_smallROI = QtWidgets.QPushButton(self.groupBox_largeROI)
        self.pushButton_smallROI.setGeometry(QtCore.QRect(60, 20, 111, 31))
        self.pushButton_smallROI.setObjectName("pushButton_smallROI")
        self.radioButtonxy = QtWidgets.QRadioButton(self.groupBox_largeROI)
        self.radioButtonxy.setGeometry(QtCore.QRect(10, 60, 71, 17))
        self.radioButtonxy.setObjectName("radioButtonxy")
        self.radioButtonxz = QtWidgets.QRadioButton(self.groupBox_largeROI)
        self.radioButtonxz.setGeometry(QtCore.QRect(80, 60, 71, 17))
        self.radioButtonxz.setObjectName("radioButtonxz")
        self.radioButtonyz = QtWidgets.QRadioButton(self.groupBox_largeROI)
        self.radioButtonyz.setGeometry(QtCore.QRect(150, 60, 71, 17))
        self.radioButtonyz.setObjectName("radioButtonyz")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_vis)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(40, 320, 281, 161))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.scatterlayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.scatterlayout_3.setContentsMargins(0, 0, 0, 0)
        self.scatterlayout_3.setObjectName("scatterlayout_3")
        self.verticalSlider = QtWidgets.QSlider(self.groupBox_vis)
        self.verticalSlider.setGeometry(QtCore.QRect(360, 50, 22, 160))
        self.verticalSlider.setMaximum(20)
        self.verticalSlider.setProperty("value", 10)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.verticalSlider.setTickInterval(2)
        self.verticalSlider.setObjectName("verticalSlider")
        self.label_24 = QtWidgets.QLabel(self.groupBox_vis)
        self.label_24.setGeometry(QtCore.QRect(340, 20, 61, 16))
        self.label_24.setObjectName("label_24")
        self.groupBox_3 = QtWidgets.QGroupBox(self.SIMPLER)
        self.groupBox_3.setGeometry(QtCore.QRect(320, 140, 191, 301))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_16.setObjectName("label_16")
        self.comboBox_selectop = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_selectop.setGeometry(QtCore.QRect(10, 40, 161, 22))
        self.comboBox_selectop.setEditable(True)
        self.comboBox_selectop.setObjectName("comboBox_selectop")
        self.textEdit_framef = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_framef.setGeometry(QtCore.QRect(10, 210, 161, 71))
        self.textEdit_framef.setLineWidth(1)
        self.textEdit_framef.setMidLineWidth(0)
        self.textEdit_framef.setObjectName("textEdit_framef")
        self.pushButton_runSIMPLER = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_runSIMPLER.setGeometry(QtCore.QRect(30, 80, 121, 91))
        self.pushButton_runSIMPLER.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_runSIMPLER.setIcon(icon)
        self.pushButton_runSIMPLER.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_runSIMPLER.setObjectName("pushButton_runSIMPLER")
        self.groupBox = QtWidgets.QGroupBox(self.SIMPLER)
        self.groupBox.setGeometry(QtCore.QRect(10, 140, 141, 171))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox_NA = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_NA.setGeometry(QtCore.QRect(10, 90, 69, 22))
        self.comboBox_NA.setEditable(True)
        self.comboBox_NA.setObjectName("comboBox_NA")
        self.lineEdit_alpha = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_alpha.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit_alpha.setObjectName("lineEdit_alpha")
        self.lineEdit_pxsize = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_pxsize.setGeometry(QtCore.QRect(10, 140, 113, 20))
        self.lineEdit_pxsize.setObjectName("lineEdit_pxsize")
        self.groupBox_files = QtWidgets.QGroupBox(self.SIMPLER)
        self.groupBox_files.setGeometry(QtCore.QRect(10, 10, 491, 121))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_files.setFont(font)
        self.groupBox_files.setFlat(False)
        self.groupBox_files.setObjectName("groupBox_files")
        self.comboBox_fileformat = QtWidgets.QComboBox(self.groupBox_files)
        self.comboBox_fileformat.setGeometry(QtCore.QRect(10, 39, 141, 22))
        self.comboBox_fileformat.setEditable(True)
        self.comboBox_fileformat.setObjectName("comboBox_fileformat")
        self.lineEdit_filename = QtWidgets.QLineEdit(self.groupBox_files)
        self.lineEdit_filename.setGeometry(QtCore.QRect(170, 40, 251, 20))
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.label_12 = QtWidgets.QLabel(self.groupBox_files)
        self.label_12.setGeometry(QtCore.QRect(10, 18, 61, 16))
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(self.groupBox_files)
        self.label_11.setGeometry(QtCore.QRect(170, 20, 47, 13))
        self.label_11.setObjectName("label_11")
        self.pushButton_browsefile = QtWidgets.QPushButton(self.groupBox_files)
        self.pushButton_browsefile.setGeometry(QtCore.QRect(430, 40, 51, 21))
        self.pushButton_browsefile.setObjectName("pushButton_browsefile")
        self.label_13 = QtWidgets.QLabel(self.groupBox_files)
        self.label_13.setGeometry(QtCore.QRect(170, 70, 161, 10))
        self.label_13.setObjectName("label_13")
        self.lineEdit_calibfilename = QtWidgets.QLineEdit(self.groupBox_files)
        self.lineEdit_calibfilename.setGeometry(QtCore.QRect(170, 90, 251, 20))
        self.lineEdit_calibfilename.setObjectName("lineEdit_calibfilename")
        self.pushButton_browsecalibfile = QtWidgets.QPushButton(self.groupBox_files)
        self.pushButton_browsecalibfile.setGeometry(QtCore.QRect(430, 90, 51, 20))
        self.pushButton_browsecalibfile.setObjectName("pushButton_browsecalibfile")
        self.checkBox_correction = QtWidgets.QCheckBox(self.groupBox_files)
        self.checkBox_correction.setGeometry(QtCore.QRect(20, 80, 131, 31))
        self.checkBox_correction.setObjectName("checkBox_correction")
        self.pushButton_updatecal = QtWidgets.QPushButton(self.SIMPLER)
        self.pushButton_updatecal.setEnabled(True)
        self.pushButton_updatecal.setGeometry(QtCore.QRect(10, 450, 110, 41))
        self.pushButton_updatecal.setObjectName("pushButton_updatecal")
        self.lineEdit_updatecal = QtWidgets.QLineEdit(self.SIMPLER)
        self.lineEdit_updatecal.setGeometry(QtCore.QRect(130, 450, 171, 41))
        self.lineEdit_updatecal.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_updatecal.setObjectName("lineEdit_updatecal")
        self.groupBox_files.raise_()
        self.lineEdit_maxdist.raise_()
        self.label_14.raise_()
        self.groupBox_2.raise_()
        self.groupBox_5.raise_()
        self.groupBox_6.raise_()
        self.groupBox_vis.raise_()
        self.groupBox_3.raise_()
        self.groupBox.raise_()
        self.pushButton_updatecal.raise_()
        self.lineEdit_updatecal.raise_()
        self.tabWidget.addTab(self.SIMPLER, "")
        self.N0caltab = QtWidgets.QWidget()
        self.N0caltab.setObjectName("N0caltab")
        self.lineEdit_filename_N0cal = QtWidgets.QLineEdit(self.N0caltab)
        self.lineEdit_filename_N0cal.setGeometry(QtCore.QRect(10, 80, 101, 20))
        self.lineEdit_filename_N0cal.setObjectName("lineEdit_filename_N0cal")
        self.label_15 = QtWidgets.QLabel(self.N0caltab)
        self.label_15.setGeometry(QtCore.QRect(10, 60, 47, 13))
        self.label_15.setObjectName("label_15")
        self.comboBox_N0calfileformat = QtWidgets.QComboBox(self.N0caltab)
        self.comboBox_N0calfileformat.setGeometry(QtCore.QRect(10, 30, 141, 22))
        self.comboBox_N0calfileformat.setEditable(True)
        self.comboBox_N0calfileformat.setObjectName("comboBox_N0calfileformat")
        self.pushButton_browsefile_N0cal = QtWidgets.QPushButton(self.N0caltab)
        self.pushButton_browsefile_N0cal.setGeometry(QtCore.QRect(120, 80, 51, 21))
        self.pushButton_browsefile_N0cal.setObjectName("pushButton_browsefile_N0cal")
        self.label_19 = QtWidgets.QLabel(self.N0caltab)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label_19.setObjectName("label_19")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.N0caltab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(390, 20, 441, 331))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_N0cal = QtWidgets.QPushButton(self.N0caltab)
        self.pushButton_N0cal.setGeometry(QtCore.QRect(40, 120, 101, 31))
        self.pushButton_N0cal.setObjectName("pushButton_N0cal")
        self.label_22 = QtWidgets.QLabel(self.N0caltab)
        self.label_22.setGeometry(QtCore.QRect(180, 60, 161, 10))
        self.label_22.setObjectName("label_22")
        self.pushButton_browsecalibfile_2 = QtWidgets.QPushButton(self.N0caltab)
        self.pushButton_browsecalibfile_2.setGeometry(QtCore.QRect(290, 80, 51, 20))
        self.pushButton_browsecalibfile_2.setObjectName("pushButton_browsecalibfile_2")
        self.lineEdit_calibfilename_2 = QtWidgets.QLineEdit(self.N0caltab)
        self.lineEdit_calibfilename_2.setGeometry(QtCore.QRect(180, 80, 101, 20))
        self.lineEdit_calibfilename_2.setObjectName("lineEdit_calibfilename_2")
        self.checkBox_correction_2 = QtWidgets.QCheckBox(self.N0caltab)
        self.checkBox_correction_2.setGeometry(QtCore.QRect(180, 30, 171, 20))
        self.checkBox_correction_2.setObjectName("checkBox_correction_2")
        self.tabWidget.addTab(self.N0caltab, "")
        self.anglealphatab = QtWidgets.QWidget()
        self.anglealphatab.setObjectName("anglealphatab")
        self.label_20 = QtWidgets.QLabel(self.anglealphatab)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.anglealphatab)
        self.label_21.setGeometry(QtCore.QRect(10, 60, 47, 13))
        self.label_21.setObjectName("label_21")
        self.lineEdit_filename_incangle = QtWidgets.QLineEdit(self.anglealphatab)
        self.lineEdit_filename_incangle.setGeometry(QtCore.QRect(10, 80, 101, 20))
        self.lineEdit_filename_incangle.setObjectName("lineEdit_filename_incangle")
        self.comboBox_incanglefileformat = QtWidgets.QComboBox(self.anglealphatab)
        self.comboBox_incanglefileformat.setGeometry(QtCore.QRect(10, 30, 141, 22))
        self.comboBox_incanglefileformat.setEditable(True)
        self.comboBox_incanglefileformat.setObjectName("comboBox_incanglefileformat")
        self.pushButton_browsefile_incangle = QtWidgets.QPushButton(self.anglealphatab)
        self.pushButton_browsefile_incangle.setGeometry(QtCore.QRect(120, 80, 51, 21))
        self.pushButton_browsefile_incangle.setObjectName("pushButton_browsefile_incangle")
        self.label_23 = QtWidgets.QLabel(self.anglealphatab)
        self.label_23.setGeometry(QtCore.QRect(180, 60, 161, 10))
        self.label_23.setObjectName("label_23")
        self.pushButton_browsecalibfile_3 = QtWidgets.QPushButton(self.anglealphatab)
        self.pushButton_browsecalibfile_3.setGeometry(QtCore.QRect(290, 80, 51, 20))
        self.pushButton_browsecalibfile_3.setObjectName("pushButton_browsecalibfile_3")
        self.lineEdit_calibfilename_3 = QtWidgets.QLineEdit(self.anglealphatab)
        self.lineEdit_calibfilename_3.setGeometry(QtCore.QRect(180, 80, 101, 20))
        self.lineEdit_calibfilename_3.setObjectName("lineEdit_calibfilename_3")
        self.checkBox_correction_3 = QtWidgets.QCheckBox(self.anglealphatab)
        self.checkBox_correction_3.setGeometry(QtCore.QRect(180, 30, 171, 20))
        self.checkBox_correction_3.setObjectName("checkBox_correction_3")
        self.tabWidget.addTab(self.anglealphatab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.rendertab = QtWidgets.QWidget()
        self.rendertab.setObjectName("rendertab")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.rendertab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(190, 30, 331, 231))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.renderlayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.renderlayout.setContentsMargins(0, 0, 0, 0)
        self.renderlayout.setObjectName("renderlayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.rendertab)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 30, 141, 251))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_mag = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_mag.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit_mag.setObjectName("lineEdit_mag")
        self.lineEdit_sigmalat = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_sigmalat.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.lineEdit_sigmalat.setObjectName("lineEdit_sigmalat")
        self.lineEdit_sigmaax = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_sigmaax.setGeometry(QtCore.QRect(10, 140, 113, 20))
        self.lineEdit_sigmaax.setObjectName("lineEdit_sigmaax")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton_render = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_render.setGeometry(QtCore.QRect(30, 180, 81, 41))
        self.pushButton_render.setObjectName("pushButton_render")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.rendertab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(190, 280, 331, 231))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.renderlayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.renderlayout_2.setContentsMargins(0, 0, 0, 0)
        self.renderlayout_2.setObjectName("renderlayout_2")
        self.tabWidget.addTab(self.rendertab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SIMPLER"))
        self.lineEdit_maxdist.setText(_translate("MainWindow", "20"))
        self.label_14.setText(_translate("MainWindow", "Frame filtering"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Fluorophore"))
        self.lineEdit_N0.setText(_translate("MainWindow", "51000"))
        self.lineEdit_lambdaem.setText(_translate("MainWindow", "700"))
        self.label_4.setText(_translate("MainWindow", "N0/Photons per frame"))
        self.label_5.setText(_translate("MainWindow", "lambda max em (nm)"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Refraction index"))
        self.lineEdit_ni.setText(_translate("MainWindow", "1.516"))
        self.lineEdit_ns.setText(_translate("MainWindow", "1.33"))
        self.label_17.setText(_translate("MainWindow", "n (incident medium)"))
        self.label_18.setText(_translate("MainWindow", "n (sample)"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Excitation"))
        self.lineEdit_angle.setText(_translate("MainWindow", "69.5"))
        self.lineEdit_lambdaex.setText(_translate("MainWindow", "642"))
        self.label_9.setText(_translate("MainWindow", "Incidence angle"))
        self.label_10.setText(_translate("MainWindow", "lambda max exc (nm)"))
        self.groupBox_vis.setTitle(_translate("MainWindow", "Visualization (output)"))
        self.groupBox_largeROI.setTitle(_translate("MainWindow", "Large ROI"))
        self.pushButton_smallROI.setText(_translate("MainWindow", "Set Small ROI"))
        self.radioButtonxy.setText(_translate("MainWindow", "Plot (x,y)"))
        self.radioButtonxz.setText(_translate("MainWindow", "Plot (x,z)"))
        self.radioButtonyz.setText(_translate("MainWindow", "Plot (y,z)"))
        self.label_24.setText(_translate("MainWindow", "Marker Size "))
        self.groupBox_3.setTitle(_translate("MainWindow", "SIMPLER analysis"))
        self.label_16.setText(_translate("MainWindow", "Select operation"))
        self.groupBox.setTitle(_translate("MainWindow", "Microscope"))
        self.label.setText(_translate("MainWindow", "alpha"))
        self.label_2.setText(_translate("MainWindow", "NA"))
        self.label_3.setText(_translate("MainWindow", "Camera pixel size"))
        self.comboBox_NA.setCurrentText(_translate("MainWindow", "1.42"))
        self.lineEdit_alpha.setText(_translate("MainWindow", "0.9"))
        self.lineEdit_pxsize.setText(_translate("MainWindow", "133"))
        self.groupBox_files.setTitle(_translate("MainWindow", "Load SMLM data and Illumination profile (if non flat illumination)"))
        self.comboBox_fileformat.setCurrentText(_translate("MainWindow", "Picasso hdf5"))
        self.label_12.setText(_translate("MainWindow", "File format"))
        self.label_11.setText(_translate("MainWindow", "Filename"))
        self.pushButton_browsefile.setText(_translate("MainWindow", "Browse"))
        self.label_13.setText(_translate("MainWindow", "Excitation profile filename"))
        self.pushButton_browsecalibfile.setText(_translate("MainWindow", "Browse"))
        self.checkBox_correction.setText(_translate("MainWindow", "correction\n"
"(non flat illumination)"))
        self.pushButton_updatecal.setText(_translate("MainWindow", "Update calibration \n"
"(dF & αF )"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SIMPLER), _translate("MainWindow", "SIMPLER"))
        self.label_15.setText(_translate("MainWindow", "Filename"))
        self.comboBox_N0calfileformat.setCurrentText(_translate("MainWindow", "Picasso hdf5"))
        self.pushButton_browsefile_N0cal.setText(_translate("MainWindow", "Browse"))
        self.label_19.setText(_translate("MainWindow", "File format"))
        self.pushButton_N0cal.setText(_translate("MainWindow", "N0 calibration"))
        self.label_22.setText(_translate("MainWindow", "Excitation profile filename"))
        self.pushButton_browsecalibfile_2.setText(_translate("MainWindow", "Browse"))
        self.checkBox_correction_2.setText(_translate("MainWindow", "correction (non flat illumination)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.N0caltab), _translate("MainWindow", "N0 Calibration"))
        self.label_20.setText(_translate("MainWindow", "File format"))
        self.label_21.setText(_translate("MainWindow", "Filename"))
        self.comboBox_incanglefileformat.setCurrentText(_translate("MainWindow", "Picasso hdf5"))
        self.pushButton_browsefile_incangle.setText(_translate("MainWindow", "Browse"))
        self.label_23.setText(_translate("MainWindow", "Excitation profile filename"))
        self.pushButton_browsecalibfile_3.setText(_translate("MainWindow", "Browse"))
        self.checkBox_correction_3.setText(_translate("MainWindow", "correction (non flat illumination)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.anglealphatab), _translate("MainWindow", "Incidence angle and alpha"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Calculate exc profile from bgd"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Rendering options"))
        self.lineEdit_mag.setText(_translate("MainWindow", "100"))
        self.lineEdit_sigmalat.setText(_translate("MainWindow", "2"))
        self.lineEdit_sigmaax.setText(_translate("MainWindow", "2"))
        self.label_6.setText(_translate("MainWindow", "Magnification"))
        self.label_7.setText(_translate("MainWindow", "Sigma (lateral)"))
        self.label_8.setText(_translate("MainWindow", "Sigma (axial)"))
        self.pushButton_render.setText(_translate("MainWindow", "Render"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rendertab), _translate("MainWindow", "Rendering"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

