# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SIMPLER_GUI_designtabs.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(970, 572)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 961, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.SIMPLER = QtWidgets.QWidget()
        self.SIMPLER.setObjectName("SIMPLER")
        self.lineEdit_maxdist = QtWidgets.QLineEdit(self.SIMPLER)
        self.lineEdit_maxdist.setGeometry(QtCore.QRect(220, 148, 41, 20))
        self.lineEdit_maxdist.setObjectName("lineEdit_maxdist")
        self.label_14 = QtWidgets.QLabel(self.SIMPLER)
        self.label_14.setGeometry(QtCore.QRect(140, 150, 81, 16))
        self.label_14.setObjectName("label_14")
        self.groupBox_2 = QtWidgets.QGroupBox(self.SIMPLER)
        self.groupBox_2.setGeometry(QtCore.QRect(130, 180, 131, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_N0 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_N0.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit_N0.setObjectName("lineEdit_N0")
        self.lineEdit_lambdaem = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_lambdaem.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.lineEdit_lambdaem.setObjectName("lineEdit_lambdaem")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_5.setObjectName("label_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.SIMPLER)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 320, 111, 121))
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_ni = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_ni.setGeometry(QtCore.QRect(10, 40, 61, 20))
        self.lineEdit_ni.setObjectName("lineEdit_ni")
        self.lineEdit_ns = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_ns.setGeometry(QtCore.QRect(10, 90, 61, 20))
        self.lineEdit_ns.setObjectName("lineEdit_ns")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_18.setObjectName("label_18")
        self.groupBox_6 = QtWidgets.QGroupBox(self.SIMPLER)
        self.groupBox_6.setGeometry(QtCore.QRect(130, 320, 131, 121))
        self.groupBox_6.setObjectName("groupBox_6")
        self.lineEdit_angle = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_angle.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.lineEdit_angle.setObjectName("lineEdit_angle")
        self.lineEdit_lambdaex = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_lambdaex.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.lineEdit_lambdaex.setObjectName("lineEdit_lambdaex")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_10.setObjectName("label_10")
        self.groupBox_vis = QtWidgets.QGroupBox(self.SIMPLER)
        self.groupBox_vis.setGeometry(QtCore.QRect(470, 10, 411, 501))
        self.groupBox_vis.setObjectName("groupBox_vis")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_vis)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 311, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.scatterlayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.scatterlayout.setContentsMargins(0, 0, 0, 0)
        self.scatterlayout.setObjectName("scatterlayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_vis)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 270, 311, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.scatterlayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.scatterlayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.scatterlayout_2.setContentsMargins(0, 0, 0, 0)
        self.scatterlayout_2.setObjectName("scatterlayout_2")
        self.groupBox_largeROI = QtWidgets.QGroupBox(self.groupBox_vis)
        self.groupBox_largeROI.setGeometry(QtCore.QRect(40, 230, 321, 261))
        self.groupBox_largeROI.setObjectName("groupBox_largeROI")
        self.pushButton_smallROI = QtWidgets.QPushButton(self.groupBox_largeROI)
        self.pushButton_smallROI.setGeometry(QtCore.QRect(90, 20, 111, 31))
        self.pushButton_smallROI.setObjectName("pushButton_smallROI")
        self.radioButtonxy = QtWidgets.QRadioButton(self.groupBox_largeROI)
        self.radioButtonxy.setGeometry(QtCore.QRect(20, 60, 71, 17))
        self.radioButtonxy.setObjectName("radioButtonxy")
        self.radioButtonxz = QtWidgets.QRadioButton(self.groupBox_largeROI)
        self.radioButtonxz.setGeometry(QtCore.QRect(110, 60, 71, 17))
        self.radioButtonxz.setObjectName("radioButtonxz")
        self.radioButtonyz = QtWidgets.QRadioButton(self.groupBox_largeROI)
        self.radioButtonyz.setGeometry(QtCore.QRect(200, 60, 71, 17))
        self.radioButtonyz.setObjectName("radioButtonyz")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_largeROI)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 90, 281, 161))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.scatterlayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.scatterlayout_3.setContentsMargins(0, 0, 0, 0)
        self.scatterlayout_3.setObjectName("scatterlayout_3")
        self.verticalSlider = QtWidgets.QSlider(self.groupBox_vis)
        self.verticalSlider.setGeometry(QtCore.QRect(360, 50, 22, 160))
        self.verticalSlider.setMaximum(20)
        self.verticalSlider.setProperty("value", 10)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.verticalSlider.setTickInterval(2)
        self.verticalSlider.setObjectName("verticalSlider")
        self.label_24 = QtWidgets.QLabel(self.groupBox_vis)
        self.label_24.setGeometry(QtCore.QRect(340, 20, 61, 16))
        self.label_24.setObjectName("label_24")
        self.groupBox_3 = QtWidgets.QGroupBox(self.SIMPLER)
        self.groupBox_3.setGeometry(QtCore.QRect(270, 140, 191, 301))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_16.setObjectName("label_16")
        self.comboBox_selectop = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_selectop.setGeometry(QtCore.QRect(10, 40, 161, 22))
        self.comboBox_selectop.setEditable(True)
        self.comboBox_selectop.setObjectName("comboBox_selectop")
        self.textEdit_framef = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_framef.setGeometry(QtCore.QRect(10, 210, 171, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_framef.setFont(font)
        self.textEdit_framef.setLineWidth(1)
        self.textEdit_framef.setMidLineWidth(0)
        self.textEdit_framef.setObjectName("textEdit_framef")
        self.pushButton_runSIMPLER = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_runSIMPLER.setGeometry(QtCore.QRect(30, 80, 121, 91))
        self.pushButton_runSIMPLER.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup/logo3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_runSIMPLER.setIcon(icon)
        self.pushButton_runSIMPLER.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_runSIMPLER.setObjectName("pushButton_runSIMPLER")
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setGeometry(QtCore.QRect(10, 190, 121, 16))
        self.label_28.setObjectName("label_28")
        self.groupBox = QtWidgets.QGroupBox(self.SIMPLER)
        self.groupBox.setGeometry(QtCore.QRect(10, 140, 111, 171))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox_NA = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_NA.setGeometry(QtCore.QRect(10, 90, 69, 22))
        self.comboBox_NA.setEditable(True)
        self.comboBox_NA.setObjectName("comboBox_NA")
        self.lineEdit_alpha = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_alpha.setGeometry(QtCore.QRect(10, 40, 71, 20))
        self.lineEdit_alpha.setObjectName("lineEdit_alpha")
        self.lineEdit_pxsize = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_pxsize.setGeometry(QtCore.QRect(10, 140, 71, 20))
        self.lineEdit_pxsize.setObjectName("lineEdit_pxsize")
        self.label_32 = QtWidgets.QLabel(self.groupBox)
        self.label_32.setGeometry(QtCore.QRect(20, 20, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Symbol")
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.groupBox_files = QtWidgets.QGroupBox(self.SIMPLER)
        self.groupBox_files.setGeometry(QtCore.QRect(10, 10, 451, 121))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_files.setFont(font)
        self.groupBox_files.setFlat(False)
        self.groupBox_files.setObjectName("groupBox_files")
        self.comboBox_fileformat = QtWidgets.QComboBox(self.groupBox_files)
        self.comboBox_fileformat.setGeometry(QtCore.QRect(10, 39, 141, 22))
        self.comboBox_fileformat.setEditable(True)
        self.comboBox_fileformat.setObjectName("comboBox_fileformat")
        self.lineEdit_filename = QtWidgets.QLineEdit(self.groupBox_files)
        self.lineEdit_filename.setGeometry(QtCore.QRect(170, 40, 211, 20))
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.label_12 = QtWidgets.QLabel(self.groupBox_files)
        self.label_12.setGeometry(QtCore.QRect(10, 18, 61, 16))
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(self.groupBox_files)
        self.label_11.setGeometry(QtCore.QRect(170, 20, 47, 13))
        self.label_11.setObjectName("label_11")
        self.pushButton_browsefile = QtWidgets.QPushButton(self.groupBox_files)
        self.pushButton_browsefile.setGeometry(QtCore.QRect(390, 40, 51, 21))
        self.pushButton_browsefile.setObjectName("pushButton_browsefile")
        self.label_13 = QtWidgets.QLabel(self.groupBox_files)
        self.label_13.setGeometry(QtCore.QRect(170, 70, 131, 16))
        self.label_13.setObjectName("label_13")
        self.lineEdit_calibfilename = QtWidgets.QLineEdit(self.groupBox_files)
        self.lineEdit_calibfilename.setGeometry(QtCore.QRect(170, 90, 211, 20))
        self.lineEdit_calibfilename.setObjectName("lineEdit_calibfilename")
        self.pushButton_browsecalibfile = QtWidgets.QPushButton(self.groupBox_files)
        self.pushButton_browsecalibfile.setGeometry(QtCore.QRect(390, 90, 51, 20))
        self.pushButton_browsecalibfile.setObjectName("pushButton_browsecalibfile")
        self.checkBox_correction = QtWidgets.QCheckBox(self.groupBox_files)
        self.checkBox_correction.setGeometry(QtCore.QRect(20, 80, 131, 31))
        self.checkBox_correction.setObjectName("checkBox_correction")
        self.pushButton_updatecal = QtWidgets.QPushButton(self.SIMPLER)
        self.pushButton_updatecal.setEnabled(True)
        self.pushButton_updatecal.setGeometry(QtCore.QRect(10, 450, 110, 41))
        self.pushButton_updatecal.setObjectName("pushButton_updatecal")
        self.lineEdit_updatecal = QtWidgets.QLineEdit(self.SIMPLER)
        self.lineEdit_updatecal.setGeometry(QtCore.QRect(130, 450, 131, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_updatecal.setFont(font)
        self.lineEdit_updatecal.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_updatecal.setObjectName("lineEdit_updatecal")
        self.groupBox_files.raise_()
        self.lineEdit_maxdist.raise_()
        self.label_14.raise_()
        self.groupBox_2.raise_()
        self.groupBox_5.raise_()
        self.groupBox_6.raise_()
        self.groupBox_vis.raise_()
        self.groupBox_3.raise_()
        self.groupBox.raise_()
        self.pushButton_updatecal.raise_()
        self.lineEdit_updatecal.raise_()
        self.tabWidget.addTab(self.SIMPLER, "")
        self.N0caltab = QtWidgets.QWidget()
        self.N0caltab.setObjectName("N0caltab")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.N0caltab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 200, 451, 301))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.layout_N0 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.layout_N0.setContentsMargins(0, 0, 0, 0)
        self.layout_N0.setObjectName("layout_N0")
        self.pushButton_N0cal = QtWidgets.QPushButton(self.N0caltab)
        self.pushButton_N0cal.setGeometry(QtCore.QRect(10, 150, 111, 31))
        self.pushButton_N0cal.setObjectName("pushButton_N0cal")
        self.groupBox_files_2 = QtWidgets.QGroupBox(self.N0caltab)
        self.groupBox_files_2.setGeometry(QtCore.QRect(10, 20, 451, 121))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_files_2.setFont(font)
        self.groupBox_files_2.setFlat(False)
        self.groupBox_files_2.setObjectName("groupBox_files_2")
        self.comboBox_N0fileformat = QtWidgets.QComboBox(self.groupBox_files_2)
        self.comboBox_N0fileformat.setGeometry(QtCore.QRect(10, 39, 141, 22))
        self.comboBox_N0fileformat.setEditable(True)
        self.comboBox_N0fileformat.setObjectName("comboBox_N0fileformat")
        self.lineEdit_N0filename = QtWidgets.QLineEdit(self.groupBox_files_2)
        self.lineEdit_N0filename.setGeometry(QtCore.QRect(170, 40, 211, 20))
        self.lineEdit_N0filename.setObjectName("lineEdit_N0filename")
        self.label_21 = QtWidgets.QLabel(self.groupBox_files_2)
        self.label_21.setGeometry(QtCore.QRect(10, 18, 61, 16))
        self.label_21.setObjectName("label_21")
        self.label_33 = QtWidgets.QLabel(self.groupBox_files_2)
        self.label_33.setGeometry(QtCore.QRect(170, 20, 47, 13))
        self.label_33.setObjectName("label_33")
        self.pushButton_N0browsefile = QtWidgets.QPushButton(self.groupBox_files_2)
        self.pushButton_N0browsefile.setGeometry(QtCore.QRect(390, 40, 51, 21))
        self.pushButton_N0browsefile.setObjectName("pushButton_N0browsefile")
        self.label_34 = QtWidgets.QLabel(self.groupBox_files_2)
        self.label_34.setGeometry(QtCore.QRect(170, 70, 131, 16))
        self.label_34.setObjectName("label_34")
        self.lineEdit_N0calibfilename = QtWidgets.QLineEdit(self.groupBox_files_2)
        self.lineEdit_N0calibfilename.setGeometry(QtCore.QRect(170, 90, 211, 20))
        self.lineEdit_N0calibfilename.setObjectName("lineEdit_N0calibfilename")
        self.pushButton_N0browsecalibfile = QtWidgets.QPushButton(self.groupBox_files_2)
        self.pushButton_N0browsecalibfile.setGeometry(QtCore.QRect(390, 90, 51, 20))
        self.pushButton_N0browsecalibfile.setObjectName("pushButton_N0browsecalibfile")
        self.checkBox_correction_2 = QtWidgets.QCheckBox(self.groupBox_files_2)
        self.checkBox_correction_2.setGeometry(QtCore.QRect(20, 80, 131, 31))
        self.checkBox_correction_2.setObjectName("checkBox_correction_2")
        self.lineEdit_updateN0 = QtWidgets.QLineEdit(self.N0caltab)
        self.lineEdit_updateN0.setGeometry(QtCore.QRect(130, 150, 221, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_updateN0.setFont(font)
        self.lineEdit_updateN0.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_updateN0.setObjectName("lineEdit_updateN0")
        self.tabWidget.addTab(self.N0caltab, "")
        self.anglealphatab = QtWidgets.QWidget()
        self.anglealphatab.setObjectName("anglealphatab")
        self.groupBox_7 = QtWidgets.QGroupBox(self.anglealphatab)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 801, 521))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(200, 20, 241, 221))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.tunelayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.tunelayout.setContentsMargins(0, 0, 0, 0)
        self.tunelayout.setObjectName("tunelayout")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(460, 20, 221, 181))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.tunelayouthist = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.tunelayouthist.setContentsMargins(0, 0, 0, 0)
        self.tunelayouthist.setObjectName("tunelayouthist")
        self.checkBox_fitcircle = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_fitcircle.setGeometry(QtCore.QRect(10, 170, 70, 17))
        self.checkBox_fitcircle.setObjectName("checkBox_fitcircle")
        self.lineEdit_D = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_D.setGeometry(QtCore.QRect(110, 170, 61, 20))
        self.lineEdit_D.setObjectName("lineEdit_D")
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_20.setObjectName("label_20")
        self.lineEdit_angletune = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_angletune.setGeometry(QtCore.QRect(10, 90, 51, 20))
        self.lineEdit_angletune.setObjectName("lineEdit_angletune")
        self.lineEdit_alphatune = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_alphatune.setGeometry(QtCore.QRect(10, 130, 41, 20))
        self.lineEdit_alphatune.setObjectName("lineEdit_alphatune")
        self.pushButton_tune = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_tune.setEnabled(True)
        self.pushButton_tune.setGeometry(QtCore.QRect(90, 90, 51, 31))
        self.pushButton_tune.setObjectName("pushButton_tune")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_9.setGeometry(QtCore.QRect(460, 210, 221, 71))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label = QtWidgets.QLabel(self.groupBox_9)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label.setObjectName("label")
        self.lineEdit_latmin = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_latmin.setGeometry(QtCore.QRect(10, 40, 41, 20))
        self.lineEdit_latmin.setObjectName("lineEdit_latmin")
        self.lineEdit_latmax = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_latmax.setGeometry(QtCore.QRect(60, 40, 41, 20))
        self.lineEdit_latmax.setObjectName("lineEdit_latmax")
        self.label_26 = QtWidgets.QLabel(self.groupBox_9)
        self.label_26.setGeometry(QtCore.QRect(130, 20, 81, 16))
        self.label_26.setObjectName("label_26")
        self.lineEdit_bin = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_bin.setGeometry(QtCore.QRect(130, 40, 41, 20))
        self.lineEdit_bin.setObjectName("lineEdit_bin")
        self.label_27 = QtWidgets.QLabel(self.groupBox_7)
        self.label_27.setGeometry(QtCore.QRect(90, 150, 111, 20))
        self.label_27.setObjectName("label_27")
        self.label_31 = QtWidgets.QLabel(self.groupBox_7)
        self.label_31.setGeometry(QtCore.QRect(14, 111, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Symbol")
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(460, 290, 311, 211))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.zlayouthist = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.zlayouthist.setContentsMargins(0, 0, 0, 0)
        self.zlayouthist.setObjectName("zlayouthist")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 240, 441, 271))
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_22 = QtWidgets.QLabel(self.groupBox_10)
        self.label_22.setGeometry(QtCore.QRect(20, 30, 81, 16))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_36 = QtWidgets.QLabel(self.groupBox_10)
        self.label_36.setGeometry(QtCore.QRect(40, 80, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Symbol")
        font.setPointSize(12)
        font.setUnderline(True)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.lineEdit_rangeang = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_rangeang.setGeometry(QtCore.QRect(10, 50, 31, 20))
        self.lineEdit_rangeang.setObjectName("lineEdit_rangeang")
        self.lineEdit_rangealpha = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_rangealpha.setGeometry(QtCore.QRect(10, 110, 31, 20))
        self.lineEdit_rangealpha.setObjectName("lineEdit_rangealpha")
        self.label_19 = QtWidgets.QLabel(self.groupBox_10)
        self.label_19.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.label_19.setObjectName("label_19")
        self.lineEdit_stepang = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_stepang.setGeometry(QtCore.QRect(60, 50, 31, 20))
        self.lineEdit_stepang.setObjectName("lineEdit_stepang")
        self.label_23 = QtWidgets.QLabel(self.groupBox_10)
        self.label_23.setGeometry(QtCore.QRect(60, 70, 47, 13))
        self.label_23.setObjectName("label_23")
        self.lineEdit_stepalpha = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_stepalpha.setGeometry(QtCore.QRect(60, 110, 31, 20))
        self.lineEdit_stepalpha.setObjectName("lineEdit_stepalpha")
        self.label_25 = QtWidgets.QLabel(self.groupBox_10)
        self.label_25.setGeometry(QtCore.QRect(10, 130, 47, 13))
        self.label_25.setObjectName("label_25")
        self.label_30 = QtWidgets.QLabel(self.groupBox_10)
        self.label_30.setGeometry(QtCore.QRect(60, 130, 47, 13))
        self.label_30.setObjectName("label_30")
        self.pushButton_tune_fit = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_tune_fit.setEnabled(True)
        self.pushButton_tune_fit.setGeometry(QtCore.QRect(20, 150, 51, 31))
        self.pushButton_tune_fit.setObjectName("pushButton_tune_fit")
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(110, 260, 331, 241))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.tunefitlayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.tunefitlayout.setContentsMargins(0, 0, 0, 0)
        self.tunefitlayout.setObjectName("tunefitlayout")
        self.pushButton_browsefile_tune = QtWidgets.QPushButton(self.anglealphatab)
        self.pushButton_browsefile_tune.setGeometry(QtCore.QRect(130, 50, 51, 21))
        self.pushButton_browsefile_tune.setObjectName("pushButton_browsefile_tune")
        self.label_29 = QtWidgets.QLabel(self.anglealphatab)
        self.label_29.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.label_29.setObjectName("label_29")
        self.lineEdit_filename_tune = QtWidgets.QLineEdit(self.anglealphatab)
        self.lineEdit_filename_tune.setGeometry(QtCore.QRect(20, 50, 101, 20))
        self.lineEdit_filename_tune.setObjectName("lineEdit_filename_tune")
        self.tabWidget.addTab(self.anglealphatab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_files_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_files_3.setGeometry(QtCore.QRect(10, 20, 451, 81))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_files_3.setFont(font)
        self.groupBox_files_3.setFlat(False)
        self.groupBox_files_3.setObjectName("groupBox_files_3")
        self.comboBox_bgfileformat = QtWidgets.QComboBox(self.groupBox_files_3)
        self.comboBox_bgfileformat.setGeometry(QtCore.QRect(10, 39, 141, 22))
        self.comboBox_bgfileformat.setEditable(True)
        self.comboBox_bgfileformat.setObjectName("comboBox_bgfileformat")
        self.lineEdit_bgfilename = QtWidgets.QLineEdit(self.groupBox_files_3)
        self.lineEdit_bgfilename.setGeometry(QtCore.QRect(170, 40, 211, 20))
        self.lineEdit_bgfilename.setObjectName("lineEdit_bgfilename")
        self.label_37 = QtWidgets.QLabel(self.groupBox_files_3)
        self.label_37.setGeometry(QtCore.QRect(10, 18, 61, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_files_3)
        self.label_38.setGeometry(QtCore.QRect(170, 20, 47, 13))
        self.label_38.setObjectName("label_38")
        self.pushButton_browsefilebg = QtWidgets.QPushButton(self.groupBox_files_3)
        self.pushButton_browsefilebg.setGeometry(QtCore.QRect(390, 40, 51, 21))
        self.pushButton_browsefilebg.setObjectName("pushButton_browsefilebg")
        self.pushButton_excprof = QtWidgets.QPushButton(self.tab)
        self.pushButton_excprof.setGeometry(QtCore.QRect(30, 110, 181, 23))
        self.pushButton_excprof.setObjectName("pushButton_excprof")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(10, 150, 451, 261))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.bgLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.bgLayout.setContentsMargins(0, 0, 0, 0)
        self.bgLayout.setObjectName("bgLayout")
        self.tabWidget.addTab(self.tab, "")
        self.rendertab = QtWidgets.QWidget()
        self.rendertab.setObjectName("rendertab")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.rendertab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(190, 20, 331, 231))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.renderlayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.renderlayout.setContentsMargins(0, 0, 0, 0)
        self.renderlayout.setObjectName("renderlayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.rendertab)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 20, 141, 271))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_mag = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_mag.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit_mag.setObjectName("lineEdit_mag")
        self.lineEdit_sigmalat = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_sigmalat.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.lineEdit_sigmalat.setObjectName("lineEdit_sigmalat")
        self.lineEdit_sigmaax = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_sigmaax.setGeometry(QtCore.QRect(10, 140, 113, 20))
        self.lineEdit_sigmaax.setObjectName("lineEdit_sigmaax")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.label_8.setObjectName("label_8")
        self.pushButton_render = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_render.setGeometry(QtCore.QRect(20, 170, 101, 91))
        self.pushButton_render.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../.designer/backup/render_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_render.setIcon(icon1)
        self.pushButton_render.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_render.setObjectName("pushButton_render")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.rendertab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(190, 270, 331, 231))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.renderlayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.renderlayout_2.setContentsMargins(0, 0, 0, 0)
        self.renderlayout_2.setObjectName("renderlayout_2")
        self.tabWidget.addTab(self.rendertab, "")
        self.TIRFangle = QtWidgets.QWidget()
        self.TIRFangle.setObjectName("TIRFangle")
        self.groupBox_files_7 = QtWidgets.QGroupBox(self.TIRFangle)
        self.groupBox_files_7.setGeometry(QtCore.QRect(10, 10, 291, 81))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_files_7.setFont(font)
        self.groupBox_files_7.setFlat(False)
        self.groupBox_files_7.setObjectName("groupBox_files_7")
        self.lineEdit_stackfile = QtWidgets.QLineEdit(self.groupBox_files_7)
        self.lineEdit_stackfile.setGeometry(QtCore.QRect(10, 40, 211, 20))
        self.lineEdit_stackfile.setObjectName("lineEdit_stackfile")
        self.label_74 = QtWidgets.QLabel(self.groupBox_files_7)
        self.label_74.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label_74.setObjectName("label_74")
        self.pushButton_browsefilebeam = QtWidgets.QPushButton(self.groupBox_files_7)
        self.pushButton_browsefilebeam.setGeometry(QtCore.QRect(230, 40, 51, 21))
        self.pushButton_browsefilebeam.setObjectName("pushButton_browsefilebeam")
        self.verticalLayoutWidget_23 = QtWidgets.QWidget(self.TIRFangle)
        self.verticalLayoutWidget_23.setGeometry(QtCore.QRect(10, 110, 311, 221))
        self.verticalLayoutWidget_23.setObjectName("verticalLayoutWidget_23")
        self.stacklayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_23)
        self.stacklayout.setContentsMargins(0, 0, 0, 0)
        self.stacklayout.setObjectName("stacklayout")
        self.pushButton_stack = QtWidgets.QPushButton(self.TIRFangle)
        self.pushButton_stack.setEnabled(True)
        self.pushButton_stack.setGeometry(QtCore.QRect(330, 40, 51, 31))
        self.pushButton_stack.setObjectName("pushButton_stack")
        self.tabWidget.addTab(self.TIRFangle, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SIMPLER"))
        self.lineEdit_maxdist.setText(_translate("MainWindow", "20"))
        self.label_14.setText(_translate("MainWindow", "Frame filtering"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Fluorophore"))
        self.lineEdit_N0.setText(_translate("MainWindow", "51000"))
        self.lineEdit_lambdaem.setText(_translate("MainWindow", "700"))
        self.label_4.setText(_translate("MainWindow", "N0/Photons per frame"))
        self.label_5.setText(_translate("MainWindow", "λ max em (nm)"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Refraction index"))
        self.lineEdit_ni.setText(_translate("MainWindow", "1.516"))
        self.lineEdit_ns.setText(_translate("MainWindow", "1.33"))
        self.label_17.setText(_translate("MainWindow", "n (incident medium)"))
        self.label_18.setText(_translate("MainWindow", "n (sample)"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Excitation"))
        self.lineEdit_angle.setText(_translate("MainWindow", "69.5"))
        self.lineEdit_lambdaex.setText(_translate("MainWindow", "642"))
        self.label_9.setText(_translate("MainWindow", "Incidence angle"))
        self.label_10.setText(_translate("MainWindow", "λ max exc (nm)"))
        self.groupBox_vis.setTitle(_translate("MainWindow", "Visualization (output)"))
        self.groupBox_largeROI.setTitle(_translate("MainWindow", "Large ROI"))
        self.pushButton_smallROI.setText(_translate("MainWindow", "Set Small ROI"))
        self.radioButtonxy.setText(_translate("MainWindow", "Plot (x,y)"))
        self.radioButtonxz.setText(_translate("MainWindow", "Plot (x,z)"))
        self.radioButtonyz.setText(_translate("MainWindow", "Plot (y,z)"))
        self.label_24.setText(_translate("MainWindow", "Marker Size "))
        self.groupBox_3.setTitle(_translate("MainWindow", "SIMPLER analysis"))
        self.label_16.setText(_translate("MainWindow", "Select operation"))
        self.label_28.setText(_translate("MainWindow", "Output after filtering locs"))
        self.groupBox.setTitle(_translate("MainWindow", "Microscope"))
        self.label_2.setText(_translate("MainWindow", "NA"))
        self.label_3.setText(_translate("MainWindow", "Camera pixel size"))
        self.comboBox_NA.setCurrentText(_translate("MainWindow", "1.42"))
        self.lineEdit_alpha.setText(_translate("MainWindow", "0.9"))
        self.lineEdit_pxsize.setText(_translate("MainWindow", "133"))
        self.label_32.setText(_translate("MainWindow", "a"))
        self.groupBox_files.setTitle(_translate("MainWindow", "Load SMLM data and Illumination profile "))
        self.comboBox_fileformat.setCurrentText(_translate("MainWindow", "Picasso hdf5"))
        self.label_12.setText(_translate("MainWindow", "File format"))
        self.label_11.setText(_translate("MainWindow", "Filename"))
        self.pushButton_browsefile.setText(_translate("MainWindow", "Browse"))
        self.label_13.setText(_translate("MainWindow", "Excitation profile filename"))
        self.pushButton_browsecalibfile.setText(_translate("MainWindow", "Browse"))
        self.checkBox_correction.setText(_translate("MainWindow", "correction\n"
"(non flat illumination)"))
        self.pushButton_updatecal.setText(_translate("MainWindow", "Update calibration \n"
"(dF & αF )"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SIMPLER), _translate("MainWindow", "SIMPLER"))
        self.pushButton_N0cal.setText(_translate("MainWindow", "N0 calibration"))
        self.groupBox_files_2.setTitle(_translate("MainWindow", "Load SMLM data and Illumination profile "))
        self.comboBox_N0fileformat.setCurrentText(_translate("MainWindow", "Picasso hdf5"))
        self.label_21.setText(_translate("MainWindow", "File format"))
        self.label_33.setText(_translate("MainWindow", "Filename"))
        self.pushButton_N0browsefile.setText(_translate("MainWindow", "Browse"))
        self.label_34.setText(_translate("MainWindow", "Excitation profile filename"))
        self.pushButton_N0browsecalibfile.setText(_translate("MainWindow", "Browse"))
        self.checkBox_correction_2.setText(_translate("MainWindow", "correction\n"
"(non flat illumination)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.N0caltab), _translate("MainWindow", "N0 Calibration"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Fine Tunning"))
        self.checkBox_fitcircle.setText(_translate("MainWindow", "Fit circle"))
        self.label_20.setText(_translate("MainWindow", "Incidence angle"))
        self.lineEdit_angletune.setText(_translate("MainWindow", "69.5"))
        self.lineEdit_alphatune.setText(_translate("MainWindow", "0.9"))
        self.pushButton_tune.setText(_translate("MainWindow", "Tune"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Histogram settings"))
        self.label.setText(_translate("MainWindow", "Lateral range"))
        self.label_26.setText(_translate("MainWindow", "Binning"))
        self.label_27.setText(_translate("MainWindow", "Diameter from fit (nm)"))
        self.label_31.setText(_translate("MainWindow", "a"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Fit for different angles and alpha"))
        self.label_22.setText(_translate("MainWindow", "Incidence angle"))
        self.label_36.setText(_translate("MainWindow", "a"))
        self.lineEdit_rangeang.setText(_translate("MainWindow", "4"))
        self.lineEdit_rangealpha.setText(_translate("MainWindow", "0.4"))
        self.label_19.setText(_translate("MainWindow", "Range"))
        self.lineEdit_stepang.setText(_translate("MainWindow", "0.5"))
        self.label_23.setText(_translate("MainWindow", "Steps"))
        self.lineEdit_stepalpha.setText(_translate("MainWindow", "0.1"))
        self.label_25.setText(_translate("MainWindow", "Range"))
        self.label_30.setText(_translate("MainWindow", "Steps"))
        self.pushButton_tune_fit.setText(_translate("MainWindow", "Run"))
        self.pushButton_browsefile_tune.setText(_translate("MainWindow", "Browse"))
        self.label_29.setText(_translate("MainWindow", "Filename"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.anglealphatab), _translate("MainWindow", "Incidence angle and alpha"))
        self.groupBox_files_3.setTitle(_translate("MainWindow", "Load SMLM data "))
        self.comboBox_bgfileformat.setCurrentText(_translate("MainWindow", "Picasso hdf5"))
        self.label_37.setText(_translate("MainWindow", "File format"))
        self.label_38.setText(_translate("MainWindow", "Filename"))
        self.pushButton_browsefilebg.setText(_translate("MainWindow", "Browse"))
        self.pushButton_excprof.setText(_translate("MainWindow", "Calculate excitation profile"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Calculate exc profile from bgd"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Rendering options"))
        self.lineEdit_mag.setText(_translate("MainWindow", "100"))
        self.lineEdit_sigmalat.setText(_translate("MainWindow", "2"))
        self.lineEdit_sigmaax.setText(_translate("MainWindow", "2"))
        self.label_6.setText(_translate("MainWindow", "Magnification"))
        self.label_7.setText(_translate("MainWindow", "Sigma (lateral)"))
        self.label_8.setText(_translate("MainWindow", "Sigma (axial)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rendertab), _translate("MainWindow", "Rendering"))
        self.groupBox_files_7.setTitle(_translate("MainWindow", "Load Image Stack"))
        self.label_74.setText(_translate("MainWindow", "Filename"))
        self.pushButton_browsefilebeam.setText(_translate("MainWindow", "Browse"))
        self.pushButton_stack.setText(_translate("MainWindow", "Beam"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TIRFangle), _translate("MainWindow", "TIRF angle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

