# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SIMPLER_GUI_design.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1094, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox_correction = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_correction.setGeometry(QtCore.QRect(190, 40, 171, 16))
        self.checkBox_correction.setObjectName("checkBox_correction")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 120, 141, 181))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox_NA = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_NA.setGeometry(QtCore.QRect(10, 90, 69, 22))
        self.comboBox_NA.setEditable(True)
        self.comboBox_NA.setObjectName("comboBox_NA")
        self.lineEdit_alpha = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_alpha.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit_alpha.setObjectName("lineEdit_alpha")
        self.lineEdit_pxsize = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_pxsize.setGeometry(QtCore.QRect(10, 150, 113, 20))
        self.lineEdit_pxsize.setObjectName("lineEdit_pxsize")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(190, 120, 131, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_N0 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_N0.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit_N0.setObjectName("lineEdit_N0")
        self.lineEdit_lambdaem = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_lambdaem.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.lineEdit_lambdaem.setObjectName("lineEdit_lambdaem")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton_runSIMPLER = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_runSIMPLER.setGeometry(QtCore.QRect(420, 450, 121, 91))
        self.pushButton_runSIMPLER.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_runSIMPLER.setIcon(icon)
        self.pushButton_runSIMPLER.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_runSIMPLER.setObjectName("pushButton_runSIMPLER")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(330, 120, 211, 321))
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_scatter = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_scatter.setGeometry(QtCore.QRect(10, 30, 81, 17))
        self.checkBox_scatter.setObjectName("checkBox_scatter")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 60, 181, 251))
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_mag = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_mag.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit_mag.setObjectName("lineEdit_mag")
        self.lineEdit_sigmalat = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_sigmalat.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.lineEdit_sigmalat.setObjectName("lineEdit_sigmalat")
        self.lineEdit_sigmaax = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_sigmaax.setGeometry(QtCore.QRect(10, 140, 113, 20))
        self.lineEdit_sigmaax.setObjectName("lineEdit_sigmaax")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.label_8.setObjectName("label_8")
        self.checkBox_zcolor = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_zcolor.setGeometry(QtCore.QRect(10, 170, 111, 17))
        self.checkBox_zcolor.setObjectName("checkBox_zcolor")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 200, 91, 17))
        self.checkBox_4.setObjectName("checkBox_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 220, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 310, 141, 131))
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_ni = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_ni.setGeometry(QtCore.QRect(10, 40, 61, 20))
        self.lineEdit_ni.setObjectName("lineEdit_ni")
        self.lineEdit_ns = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_ns.setGeometry(QtCore.QRect(10, 90, 61, 20))
        self.lineEdit_ns.setObjectName("lineEdit_ns")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_18.setObjectName("label_18")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(190, 250, 131, 121))
        self.groupBox_6.setObjectName("groupBox_6")
        self.lineEdit_angle = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_angle.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.lineEdit_angle.setObjectName("lineEdit_angle")
        self.lineEdit_lambdaex = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_lambdaex.setGeometry(QtCore.QRect(10, 90, 113, 20))
        self.lineEdit_lambdaex.setObjectName("lineEdit_lambdaex")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(10, 70, 111, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 70, 47, 13))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(190, 70, 161, 20))
        self.label_13.setObjectName("label_13")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(80, 450, 91, 16))
        self.label_16.setObjectName("label_16")
        self.comboBox_fileformat = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_fileformat.setGeometry(QtCore.QRect(20, 40, 141, 22))
        self.comboBox_fileformat.setEditable(True)
        self.comboBox_fileformat.setObjectName("comboBox_fileformat")
        self.comboBox_selectop = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_selectop.setGeometry(QtCore.QRect(80, 470, 321, 22))
        self.comboBox_selectop.setEditable(True)
        self.comboBox_selectop.setObjectName("comboBox_selectop")
        self.lineEdit_updatecal = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_updatecal.setGeometry(QtCore.QRect(190, 430, 121, 20))
        self.lineEdit_updatecal.setObjectName("lineEdit_updatecal")
        self.pushButton_browsefile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browsefile.setGeometry(QtCore.QRect(130, 90, 51, 21))
        self.pushButton_browsefile.setObjectName("pushButton_browsefile")
        self.lineEdit_filename = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_filename.setGeometry(QtCore.QRect(20, 90, 101, 20))
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.pushButton_updatecal = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_updatecal.setEnabled(True)
        self.pushButton_updatecal.setGeometry(QtCore.QRect(190, 380, 121, 41))
        self.pushButton_updatecal.setObjectName("pushButton_updatecal")
        self.lineEdit_calibfilename = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_calibfilename.setGeometry(QtCore.QRect(190, 90, 101, 20))
        self.lineEdit_calibfilename.setObjectName("lineEdit_calibfilename")
        self.pushButton_browsecalibfile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_browsecalibfile.setGeometry(QtCore.QRect(300, 90, 51, 23))
        self.pushButton_browsecalibfile.setObjectName("pushButton_browsecalibfile")
        self.lineEdit_maxdist = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_maxdist.setGeometry(QtCore.QRect(380, 90, 113, 20))
        self.lineEdit_maxdist.setObjectName("lineEdit_maxdist")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(380, 70, 111, 16))
        self.label_14.setObjectName("label_14")
        self.groupBox_vis = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_vis.setGeometry(QtCore.QRect(550, 30, 471, 511))
        self.groupBox_vis.setObjectName("groupBox_vis")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_vis)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 20, 271, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.scatterlayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.scatterlayout.setContentsMargins(0, 0, 0, 0)
        self.scatterlayout.setObjectName("scatterlayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_vis)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(150, 280, 271, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.scatterlayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.scatterlayout_2.setContentsMargins(0, 0, 0, 0)
        self.scatterlayout_2.setObjectName("scatterlayout_2")
        self.groupBox_largeROI = QtWidgets.QGroupBox(self.groupBox_vis)
        self.groupBox_largeROI.setGeometry(QtCore.QRect(10, 260, 131, 91))
        self.groupBox_largeROI.setObjectName("groupBox_largeROI")
        self.pushButton_smallROI = QtWidgets.QPushButton(self.groupBox_largeROI)
        self.pushButton_smallROI.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.pushButton_smallROI.setObjectName("pushButton_smallROI")
        self.pushButton_xz = QtWidgets.QPushButton(self.groupBox_largeROI)
        self.pushButton_xz.setGeometry(QtCore.QRect(0, 60, 61, 23))
        self.pushButton_xz.setObjectName("pushButton_xz")
        self.pushButton_yz = QtWidgets.QPushButton(self.groupBox_largeROI)
        self.pushButton_yz.setGeometry(QtCore.QRect(70, 60, 61, 23))
        self.pushButton_yz.setObjectName("pushButton_yz")
        self.textEdit_framef = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_framef.setGeometry(QtCore.QRect(150, 500, 251, 41))
        self.textEdit_framef.setLineWidth(1)
        self.textEdit_framef.setMidLineWidth(0)
        self.textEdit_framef.setObjectName("textEdit_framef")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1094, 21))
        self.menubar.setObjectName("menubar")
        self.menuSIMPLER = QtWidgets.QMenu(self.menubar)
        self.menuSIMPLER.setObjectName("menuSIMPLER")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSIMPLER.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_correction.setText(_translate("MainWindow", "correction (non flat illumination)"))
        self.groupBox.setTitle(_translate("MainWindow", "Microscope"))
        self.label.setText(_translate("MainWindow", "alpha"))
        self.label_2.setText(_translate("MainWindow", "NA"))
        self.label_3.setText(_translate("MainWindow", "Camera pixel size"))
        self.comboBox_NA.setCurrentText(_translate("MainWindow", "1.42"))
        self.lineEdit_alpha.setText(_translate("MainWindow", "0.9"))
        self.lineEdit_pxsize.setText(_translate("MainWindow", "133"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Fluorophore"))
        self.lineEdit_N0.setText(_translate("MainWindow", "51000"))
        self.lineEdit_lambdaem.setText(_translate("MainWindow", "700"))
        self.label_4.setText(_translate("MainWindow", "N0/Photons per frame"))
        self.label_5.setText(_translate("MainWindow", "lambda max em (nm)"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Visualization"))
        self.checkBox_scatter.setText(_translate("MainWindow", "Scatter plot"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Rendering"))
        self.label_6.setText(_translate("MainWindow", "Magnification"))
        self.label_7.setText(_translate("MainWindow", "Sigma (lateral)"))
        self.label_8.setText(_translate("MainWindow", "Sigma (axial)"))
        self.checkBox_zcolor.setText(_translate("MainWindow", "z-color rendering"))
        self.checkBox_4.setText(_translate("MainWindow", "auto-contrast"))
        self.pushButton_2.setText(_translate("MainWindow", "Render"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Refraction index"))
        self.lineEdit_ni.setText(_translate("MainWindow", "1.51"))
        self.lineEdit_ns.setText(_translate("MainWindow", "1.33"))
        self.label_17.setText(_translate("MainWindow", "n (incident medium)"))
        self.label_18.setText(_translate("MainWindow", "n (sample)"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Excitation"))
        self.lineEdit_angle.setText(_translate("MainWindow", "69"))
        self.lineEdit_lambdaex.setText(_translate("MainWindow", "642"))
        self.label_9.setText(_translate("MainWindow", "Incidence angle"))
        self.label_10.setText(_translate("MainWindow", "lambda max exc (nm)"))
        self.label_11.setText(_translate("MainWindow", "Filename"))
        self.label_12.setText(_translate("MainWindow", "File format"))
        self.label_13.setText(_translate("MainWindow", "Excitation profile filename"))
        self.label_16.setText(_translate("MainWindow", "Select operation"))
        self.comboBox_fileformat.setCurrentText(_translate("MainWindow", "Picasso hdf5"))
        self.pushButton_browsefile.setText(_translate("MainWindow", "Browse"))
        self.pushButton_updatecal.setText(_translate("MainWindow", "Update calibration \n"
"(dF & alphaF )"))
        self.pushButton_browsecalibfile.setText(_translate("MainWindow", "Browse"))
        self.lineEdit_maxdist.setText(_translate("MainWindow", "20"))
        self.label_14.setText(_translate("MainWindow", "Frame filtering"))
        self.groupBox_vis.setTitle(_translate("MainWindow", "Visualization (output)"))
        self.groupBox_largeROI.setTitle(_translate("MainWindow", "Large ROI"))
        self.pushButton_smallROI.setText(_translate("MainWindow", "Set Small ROI"))
        self.pushButton_xz.setText(_translate("MainWindow", "Plot (x,z)"))
        self.pushButton_yz.setText(_translate("MainWindow", "Plot (y,z)"))
        self.menuSIMPLER.setTitle(_translate("MainWindow", "SIMPLER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

